from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path
import re
from xml.sax.saxutils import escape
from zipfile import ZIP_DEFLATED, ZipFile

from ..llm import BaseLLM
from ..schemas import RegulatoryItem


def load_regulatory_items(path: str | Path) -> list[RegulatoryItem]:
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    return [RegulatoryItem(**item) for item in raw]


def enrich_regulatory_items(items: list[RegulatoryItem], llm: BaseLLM) -> list[RegulatoryItem]:
    enriched: list[RegulatoryItem] = []
    for item in items:
        prompt = (
            "Classify the regulatory news into licensing, enforcement, aml, market conduct, "
            "or general compliance. Return JSON with category, risk_level, summary.\n\n"
            f"Title: {item.title}\nBody: {item.body}"
        )
        response = llm.complete("You are a compliance analyst for a securities firm.", prompt)
        payload = _safe_json(response.text)
        item.category = payload.get("category") or classify_item(item)
        item.risk_level = payload.get("risk_level") or risk_level(item)
        item.summary = payload.get("summary") or summarize_item(item)
        item.obligations = extract_obligations(item)
        item.action_owner = route_owner(item)
        enriched.append(item)
    return enriched


def classify_item(item: RegulatoryItem) -> str:
    text = f"{item.title} {item.body}".lower()
    rules = [
        ("aml", ["anti-money", "money laundering", "aml", "customer due diligence", "transaction monitoring", "反洗钱"]),
        ("enforcement", ["disciplinary", "reprimand", "fine", "penalty", "breach", "sanction", "处分", "罚款"]),
        ("market conduct", ["market", "trading", "short selling", "disclosure", "surveillance", "交易", "披露"]),
        ("licensing", ["license", "licensing", "representative", "responsible officer", "牌照", "持牌"]),
    ]
    for category, keywords in rules:
        if any(keyword in text for keyword in keywords):
            return category
    return "general compliance"


def risk_level(item: RegulatoryItem) -> str:
    category = item.category or classify_item(item)
    if category in {"enforcement", "aml"}:
        return "high"
    if category in {"market conduct", "licensing"}:
        return "medium"
    return "low"


def summarize_item(item: RegulatoryItem) -> str:
    text = re.sub(r"\s+", " ", item.body).strip()
    sentences = re.split(r"(?<=[.!?。！？])\s*", text)
    return " ".join(sentences[:2])[:420]


def extract_obligations(item: RegulatoryItem) -> list[str]:
    category = item.category or classify_item(item)
    obligations = {
        "aml": [
            "Review CDD and EDD procedures for high-risk clients",
            "Check transaction monitoring alerts and escalation evidence",
        ],
        "enforcement": [
            "Assess whether internal controls match the enforcement facts",
            "Prepare management briefing and remediation tracker",
        ],
        "market conduct": [
            "Review trading surveillance scenarios and alert thresholds",
            "Retain evidence for suspicious order pattern escalation",
        ],
        "licensing": [
            "Check responsible officer and representative competence records",
            "Update licensing notification checklist",
        ],
        "general compliance": [
            "Archive notice and assign compliance owner for review",
        ],
    }
    return obligations.get(category, obligations["general compliance"])


def route_owner(item: RegulatoryItem) -> str:
    category = item.category or classify_item(item)
    return {
        "aml": "financial-crime-compliance",
        "enforcement": "compliance-governance",
        "market conduct": "trading-compliance",
        "licensing": "licensing-team",
    }.get(category, "compliance")


def write_digest_docx(items: list[RegulatoryItem], output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = [
        paragraph("SFC Regulatory Digest"),
        paragraph("Generated by multi-agent compliance workflow."),
        paragraph("Sections: category, risk level, summary, obligations, owner, source link."),
    ]
    for item in items:
        body.extend(
            [
                paragraph(f"{item.published_at} | {item.category.upper()} | {item.risk_level.upper()}"),
                paragraph(item.title),
                paragraph(f"Summary: {item.summary}"),
                paragraph(f"Owner: {item.action_owner}"),
                paragraph("Obligations:"),
            ]
        )
        body.extend(paragraph(f"- {obligation}") for obligation in item.obligations)
        body.append(paragraph(f"Source: {item.url}"))
    document_xml = _document_xml("\n".join(body))
    with ZipFile(path, "w", ZIP_DEFLATED) as docx:
        docx.writestr("[Content_Types].xml", CONTENT_TYPES)
        docx.writestr("_rels/.rels", RELS)
        docx.writestr("word/_rels/document.xml.rels", DOCUMENT_RELS)
        docx.writestr("word/document.xml", document_xml)
    return path


def write_digest_json(items: list[RegulatoryItem], output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps([asdict(item) for item in items], ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def _safe_json(text: str) -> dict:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {}


def paragraph(text: str) -> str:
    return f"<w:p><w:r><w:t>{escape(text)}</w:t></w:r></w:p>"


def _document_xml(body: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        f"<w:body>{body}<w:sectPr/></w:body></w:document>"
    )


CONTENT_TYPES = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>"""

RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>"""

DOCUMENT_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>"""
